config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Enter the new task title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, placeholder: "Enter the new task details", class: "form-control" %>
  </div>
  <div class='form-group'>
    <% if !task.new_record?%>
    <%= f.check_box :completed %>
    <%= f.label :completed %>
    <% end %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', task: @task %>

<i class="fas fa-undo-alt"></i>
<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task|%>
    <li>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task)%>
      <%= link_to "Delete", task_path(task), method: :delete, data: {confirm: "Delete #{task.title}?"}, class: "btn btn-danger" %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path, class: "btn btn-primary"%>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

<i class="fas fa-undo-alt"></i>
<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<div class="edit-title d-flex justify-content-between align-items-center">
  <h1><%= @task.title %></h1>
  <%= link_to "Edit this task", task_edit_path, class: "btn btn-primary" %>
</div>

<p class="alert alert-info"><%= @task.details %></p>

<p>
  <% if @task.completed %>
    <i class="far fa-check-square"></i>
    <%= "This task is completed "%>
  <% else %>
    <i class="far fa-square"></i>
    <%= "This task is not completed yet" %>
  <% end %>
</p>

<i class="fas fa-undo-alt"></i>
<%= link_to "Back to list", tasks_path%>